import styles from "@styles/login.module.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Log in - Spotify",
	description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body
				className={`bg-gradient-to-b from-zinc-800 via-zinc-900  ${styles.login}`}
			>
				{children}
			</body>
		</html>
	);
}
