import "@/app/globals.css";
import styles from "@styles/login.module.css";
import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
	title: "Log in - Spotify",
	description: "Generated by create next app",
};

export default function Layout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<body
				className={`bg-gradient-to-b from-neutral-800 via-neutral-900 to-zinc-950  ${styles.login}`}
			>
				{children}
			</body>
		</html>
	);
}
