import Player from "@/components/player";
import AuthProvider from "@/providers/auth-provider";
import SliderProvider from "@/providers/slider-provider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Spotify Clone",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<AuthProvider>
			<html lang="en">
				<body>
					<SliderProvider>{children}</SliderProvider>
					<Player />
				</body>
			</html>
		</AuthProvider>
	);
}
