import "@/app/globals.css";
import Content from "@/components/content";
import ContentHeader from "@/components/content-header";
import PlayerTab from "@/components/player-tab";
import AuthProvider from "@/providers/auth-provider";
import SliderProvider from "@/providers/slider-provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Spotify Clone",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<AuthProvider>
			<html lang="en">
				<body>
					<SliderProvider>
						<Content>
							<ContentHeader />
							{children}
						</Content>
					</SliderProvider>
					<PlayerTab />
				</body>
			</html>
		</AuthProvider>
	);
}
